
arr = [2, 3, 5, 7, 11, 13, 17, 19]
new_arr = []

for item in arr:
    new_arr.append(item + 1)

for item in arr:
    if item % 4 == 1:
        new_arr.append(item)

result = ''
for item in arr:
    result += str(item) + ','

for item in arr:
    new_arr.append(1)

for item in arr:
    if item % 4 == 1:
        new_arr.append(2)

result = ''
for item in arr:
    result += str(3) + ','

primes = arr
print(sum([p for p in primes if p >= 10]))
print(max([p for p in primes if p % 3 == 2]))
print(min([p for p in primes if p % 3 == 1]))
print(all([p % 2 == 1 for p in primes]))
print(any([p % 2 == 1 for p in primes]))

print(sum(p for p in primes if p >= 10))
print(max(p for p in primes if p % 3 == 2))
print(min(p for p in primes if p % 3 == 1))
print(all(p % 2 == 1 for p in primes))
print(any(p % 2 == 1 for p in primes))

test = 0
if test >= 100:
    print('large', 'S')
elif test >= 75:
    print('medium', 'A')
elif test >= 50:
    print('small', 'B')
else:
    print('tiny', 'C')

test_abc = 0
if test_abc >= 100:
    print('large', 'S')
elif test >= 75:
    print('medium', 'A')
elif test_abc >= 50:
    print('small', 'B')
else:
    print('tiny', 'C')

test_def = 0
if test_def >= 100:
    print('large', 'S')
elif test_def >= 75:
    print('medium', 'A')
elif test_def >= 50:
    print('small', 'B', 'passed')
else:
    print('tiny', 'C')

if test >= 100 and True:
    print('aaa')
elif test <= 75 and False:
    print('bbb')
else:
    print('ccc')

path = 'ab/cd/efg/hij.csv'
non_path = 'aaa/bbb/ccc'

# Generated by Google Search: "불필요한 변수 생성 대신 defaultdict 를 사용하면 좋은 경우"
data = [('과일', '사과'), ('채소', '당근'), ('과일', '바나나')]
groups = {}

for category, item in data:
    if category not in groups:
        groups[category] = []  # 빈 리스트 변수/값 생성 필요
    groups[category].append(item)

words = ['apple', 'banana', 'apple']
counts = {}

for word in words:
    if word not in counts:
        counts[word] = 0  # 초기값 0 설정 필요
    counts[word] += 1

test_dict = {}
test_dict['abc'] = ''
test_dict['def'] = ""

# Generated by Google Search: "python any all 패턴으로 리팩토링 예제"
numbers = [1, 2, 3, -4, 5]

has_negative = False
for num in numbers:
    if num < 0:
        has_negative = True
        break

print(has_negative)  # True

# Generated by Google Search
names = ["Alice", "Bob", "Charlie"]
scores = [85, 92, 78]

for i in range(len(names)):
    print(f"{names[i]}의 점수는 {scores[i]}점입니다.")

keys = ["id", "name", "role"]
values = [101, "John", "Admin"]

user_info = {}
for i in range(len(keys)):
    user_info[keys[i]] = values[i]

# Generated using Gemini + keys -> values
for i in range(len(values)):
    user_info[keys[i]] = values[i]

k_list = keys
v_list = values
target = {}

for idx in range(len(k_list)):
    k = k_list[idx]
    v = v_list[idx]
    target[k] = v

for itertool1 in range(100):
    for itertool2 in range(len(target)):
        print(400)

with open('example1.txt', 'r', encoding='utf-8') as f:
    content1 = f.read()

with open('example2.txt', 'w', encoding='utf-8') as f:
    f.write(content1)

with open('example3.txt', 'r') as f:
    content2 = f.read()

with open('example4.txt', 'w') as f:
    f.write(content2)

sentence = '123'
if len(sentence):
    print(1)
if not len(sentence):
    print(2)
if len(sentence) == 0:
    print(3)
if not len(sentence) == 0:
    print(4)
if sentence == '':
    print(5)
if not sentence == '':
    print(6)
if sentence:
    print(7)
if not sentence:
    print(8)

a = {}
dddd = 'b' in a and a['b'] is not None
eeee = dddd in a and a[dddd] is not None
if 'b' in a and a['b'] is not None:
    print(a)

if 'b' in a and a['b']:
    print(a)

'b' in a and a['b'] is not None
'b' in a and a['b']

# Generated by Google Search
fruits = ["apple", "banana"]
new_fruits = ["cherry", "grape", "orange"]

for fruit in new_fruits:
    fruits.append(fruit)


def collect_user_ids(active_users, new_users):
    # += 연산자도 작동하지만, 직관적인 메서드 명시가 필요할 때
    active_users += [user.id for user in new_users]
    return active_users


apple_count = 0
for fruit in fruits:
    if fruit == "apple":
        apple_count += 1


scores = [100, 85, 90, 100, 75, 100]

# 필터링된 리스트를 메모리에 새로 생성하므로 비효율적
perfect_scores = len([score for score in scores if score == 100])


users = ["admin", "guest", "user", "admin"]

# 함수 호출이 많고 가독성이 떨어짐
admin_count = len(list(filter(lambda x: x == "admin", users)))

# index 예제들

target = "apple"
items = ["banana", "orange", "apple", "grape"]
found_index = -1
for i in range(len(items)):
    if items[i] == target:
        found_index = i
        break


found_index = -1
for i in range(len(items)):
    if items[i] == "apple":
        found_index = i
        break


found_index = 0
for i in range(len(items)):
    if items[i] == "apple":
        found_index = i
        break

target = 40
numbers = [10, 20, 30, 40, 50]
idx = next(i for i, v in enumerate(numbers) if v == target)

strs = ['a', 'b', 'c', 'd', 'e']
idx = next(i for i, v in enumerate(strs) if v == 'e')

target = "search_me"
data = ["raw", "data", "search_me", "end"]
i = 0
while i < len(data):
    if data[i] == target:
        break
    i += 1


i = 0
while i < len(data):
    if data[i] == "search_me":
        break
    i += 1
