
arr = [2, 3, 5, 7, 11, 13, 17, 19]
new_arr = []

for item in arr:
    new_arr.append(item + 1)

for item in arr:
    if item % 4 == 1:
        new_arr.append(item)

result = ''
for item in arr:
    result += str(item) + ','

for item in arr:
    new_arr.append(1)

for item in arr:
    if item % 4 == 1:
        new_arr.append(2)

result = ''
for item in arr:
    result += str(3) + ','

primes = arr
print(sum([p for p in primes if p >= 10]))
print(max([p for p in primes if p % 3 == 2]))
print(min([p for p in primes if p % 3 == 1]))
print(all([p % 2 == 1 for p in primes]))
print(any([p % 2 == 1 for p in primes]))

print(sum(p for p in primes if p >= 10))
print(max(p for p in primes if p % 3 == 2))
print(min(p for p in primes if p % 3 == 1))
print(all(p % 2 == 1 for p in primes))
print(any(p % 2 == 1 for p in primes))

test = 0
if test >= 100:
    print('large', 'S')
elif test >= 75:
    print('medium', 'A')
elif test >= 50:
    print('small', 'B')
else:
    print('tiny', 'C')

test_abc = 0
if test_abc >= 100:
    print('large', 'S')
elif test >= 75:
    print('medium', 'A')
elif test_abc >= 50:
    print('small', 'B')
else:
    print('tiny', 'C')

test_def = 0
if test_def >= 100:
    print('large', 'S')
elif test_def >= 75:
    print('medium', 'A')
elif test_def >= 50:
    print('small', 'B', 'passed')
else:
    print('tiny', 'C')

if test >= 100 and True:
    print('aaa')
elif test <= 75 and False:
    print('bbb')
else:
    print('ccc')

path = 'ab/cd/efg/hij.csv'
non_path = 'aaa/bbb/ccc'

# Generated by Google Search: "불필요한 변수 생성 대신 defaultdict 를 사용하면 좋은 경우"
data = [('과일', '사과'), ('채소', '당근'), ('과일', '바나나')]
groups = {}

for category, item in data:
    if category not in groups:
        groups[category] = []  # 빈 리스트 변수/값 생성 필요
    groups[category].append(item)

words = ['apple', 'banana', 'apple']
counts = {}

for word in words:
    if word not in counts:
        counts[word] = 0  # 초기값 0 설정 필요
    counts[word] += 1


test_dict = {}
test_dict['abc'] = ''
test_dict['def'] = ""
