name: effiSegNetBN
object:
  _target_: effisegnet_improved.effisegnet.EffiSegNetBN
  ch: ${ch}
  pretrained: ${pretrained}
  freeze_encoder: ${freeze_encoder}
  deep_supervision: ${deep_supervision}
  model_name: ${model_name}
